<?php
/**
 * @author wsfuyibing <websearch@163.com>
 * @date 2018-03-19
 */
namespace App\Models\Abstracts;

use Uniondrug\Framework\Models\Model as FrameworkModel;

/**
 * @package App\Models
 */
abstract class Model extends FrameworkModel
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}
