<?php
return [
    "development" => [
        "wxapi_host"    => "http://wxapi.ud.dovecot.cn",
        "app_host"      => "http://app.ud.dovecot.cn",
        "common_host"   => "http://common.ud.dovecot.cn",
        "admin_host"    => "http://admin.turboradio.cn",
        'activity_host' => 'http://121.40.199.140:7777',
        'cms_url'       => 'http://cms.uniondrug.cn',
        'report_host'   => "http://121.40.199.140:9988",
        'policy_host'   => "http://121.40.199.140:12301",
        'wx_host'       => "http://wx.ud.dovecot.cn",
        'service_host'  => "http://121.40.199.140:9100",
        'sms_host'      => 'http://121.40.199.140:9100/api/sms/send',
        'data_host'     => 'http://data.turbomedia.cn',
        'erp_host'      => 'http://erp.ud.dovecot.cn',
        'rights_host'   => 'http://rights.service.turbomedia.cn',
        'partner_host'  => 'http://test.common.turbomedia.cn',
        'equity_host'   => 'http://equity.module.dev.turboradio.cn/'
    ],
    'testing'     => [
        "wxapi_host"    => "http://wxapi.turboradio.cn/",
        "app_host"      => "http://app.turboradio.cn",
        "common_host"   => "http://common.turboradio.cn",
        "admin_host"    => "http://admin.turboradio.cn",
        'activity_host' => 'http://121.40.199.140:7777',
        'cms_url'       => 'http://cms.uniondrug.cn',
        'report_host'   => "http://121.40.199.140:9988",
        'policy_host'   => "http://121.40.199.140:12301",
        'wx_host'       => "http://wx.turboradio.cn",
        'service_host'  => "http://121.40.199.140:9101",
        'sms_host'      => 'http://121.40.199.140:9101/api/sms/send',
        'data_host'     => 'http://data.turboradio.cn',
        'erp_host'      => 'http://erp.turboradio.cn',
        'rights_host'   => 'http://rights.service.turbomedia.cn',
        'partner_host'  => 'http://test.common.turbomedia.cn',
        'equity_host'   => 'http://equity.module.dev.turboradio.cn/'
    ],
    "production"  => [
        'sms_host'      => 'http://121.40.203.138:10081/api/sms/send',
        "wxapi_host"    => "http://wxapi.uniondrug.cn",
        "app_host"      => "http://app.uniondrug.cn",
        "common_host"   => "http://common.uniondrug.cn",
        "admin_host"    => "http://admin.uniondrug.cn",
        'activity_host' => 'http://121.40.203.138:10080',
        'cms_url'       => 'http://cms.uniondrug.cn',
        'report_host'   => "http://report.uniondrug.cn",
        'policy_host'   => "http://yjk.1bao.me",
        'wx_host'       => "http://wx.uniondrug.cn",
        'service_host'  => "http://service.uniondrug.cn",
        'data_host'     => 'http://data.uniondrug.cn',
        'erp_host'      => 'http://erp.uniondrug.cn',
        'rights_host'   => 'http://rights.service.uniondrug.cn',
        'partner_host'  => 'http://common.uniondrug.cn',
        'equity_host'   => 'http://equity.module.dev.turboradio.cn/'
    ]
];