<?php
/**
 * Created by PhpStorm.
 * User: qishengqiang
 * Date: 2018/5/22
 * Time: 下午3:17
 */

namespace App\Models;

use Phalcon\Di;
use App\Models\Abstracts\Model;

class BaseModel extends Model
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}