<?php
/**
 * Created by PhpStorm.
 * User: qishengqiang
 * Date: 2018/5/3
 * Time: 下午3:35
 */

namespace App\Models;


use App\Models\Abstracts\Model;

class Communicates extends BaseModel
{
    CONST FINISH = 1;

    CONST UNFINISH = 0;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setConnectionService("db2");
    }

    public function getFromPlatText()
    {
        switch($this->fromPlat){
            case 1:
                $text = "电话";
                break;
            case 2:
                $text = "微信";
                break;
        }

        return $text;
    }
}