<?php
/**
 * Created by PhpStorm.
 * User: qishengqiang
 * Date: 2018/5/3
 * Time: 下午3:35
 */

namespace App\Models;


use App\Models\Abstracts\Model;

class Communicates extends BaseModel
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setConnectionService("db2");
    }
}