<?php
/**
 * Created by PhpStorm.
 * User: qishengqiang
 * Date: 2018/6/1
 * Time: 下午4:34
 */

namespace App\Models;


use App\Models\Abstracts\Model;

class PoolRecords extends Model
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setConnectionService("db1");
    }
}