<?php
/**
 * Created by PhpStorm.
 * User: qishengqiang
 * Date: 2018/5/3
 * Time: 下午3:35
 */

namespace App\Models;


use App\Models\Abstracts\Model;

class UgCategories extends Model
{
    CONST HUANYAO = 1;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}