<?php
/**
 * Created by PhpStorm.
 * User: qishengqiang
 * Date: 2018/5/3
 * Time: 下午3:35
 */

namespace App\Models;


use App\Models\Abstracts\Model;

class UgOrderRecords extends Model
{
    CONST ORDER_ACTIVATE = 1;  //待激活,用户资料不全
    CONST ORDER_ADDING = 0; //是未支付状态
    CONST ORDER_CHECKING = 3; //待审核
    CONST ORDER_PASSED = 2; //审核通过
    CONST ORDER_NOPASS = 4; //审核未通过
    CONST ORDER_CANCEL = -1; //撤销的单子

    CONST ORDER_MODE_FILL = 1;
    CONST ORDER_MODE_JISU = 2;
    CONST ORDER_MODE_DIRECT = 3;

    CONST IS_DIRECT = 1;
    CONST ISNOT_DIRECT = 0;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->hasOne(
            'order_no',
            __NAMESPACE__.'\\UgOrderErps',
            'order_no',
            [
                'alias' => 'orderErp'
            ]
        );

        $this->hasOne(
            'partner_id',
            __NAMESPACE__.'\\Partners',
            'id',
            [
                'alias' => 'partner'
            ]
        );

        $this->hasOne(
            'store_id',
            __NAMESPACE__.'\\Stores',
            'id',
            [
                'alias' => 'store'
            ]
        );

        $this->hasOne(
            'order_no',
            __NAMESPACE__.'\\UgOrderUdcard',
            'order_no',
            [
                'alias' => 'orderCard'
            ]
        );

        $this->hasOne(
            'member_id',
            __NAMESPACE__.'\\WxMembers',
            'id',
            [
                'alias' => 'member'
            ]
        );

        $this->hasMany(
            'order_no',
            __NAMESPACE__.'\\UgOrderItems',
            'order_no',
            [
                'alias' => 'items'
            ]
        );
    }

    //判断药品是否全部可保
    public function countItems(){
        $items = $this->items;
        $pass = 0;
        $unpass = 0;
        if($items){
            foreach($items as $item){
                if($item->is_guarantee == 1){
                    $pass++;
                }else{
                    if($item->batch_number != 'None'){
                        $unpass++;
                    }
                }
            }
        }
        return [
            'pass_count' => $pass,
            'unpass_count' => $unpass
        ];
    }
}