<?php
/**
 * Created by PhpStorm.
 * User: qishengqiang
 * Date: 2018/5/3
 * Time: 下午3:35
 */

namespace App\Models;


use App\Models\Abstracts\Model;

class UgShopCartRecords extends Model
{
    public function getSource()
    {
        return 'ug_shopCart_records';
    }

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->hasOne(
            'id',
            __NAMESPACE__.'\\UgShopsExpress',
            'cart_id',
            [
                'alias' => 'express'
            ]
        );
    }

    public function getStatusText()
    {
        $arr = ['0' => '未下单', '1' => '已下单', '2' => '药店已发货', '3' => '退款'];

        return $arr[$this->status];
    }
}